### PR TITLE
Strip all files so the executables are smaller

### PR DESCRIPTION
**Pull request by AMTitan**
Testing it with the agent it decreased in size by 88%.

### CODE REVIEW

**Comment by BigBoot** [comment]
Hi and thanks for your contribution.
The releases are currently build on windows runners, do you know if strip is available there?

**Comment by AMTitan** [comment]
Is there a reason that the build runs on windows? I am guessing it has to do with [this].(https://github.com/BigBoot/GiganticEmu/blob/master/.github/workflows/release.yaml#L21-L27)

**Comment by AMTitan** [comment]
Also correct me if I am wrong, but you could also strip in the "release" portion, [here](https://github.com/BigBoot/GiganticEmu/blob/master/.github/workflows/release.yaml#L50).

**Comment by BigBoot** [comment]
The ArcSDK.dll build needs windows, I think best would be to wrap the `strip` call in a 
```pwsh
if (Get-Command "strip" -ErrorAction SilentlyContinue) 
{ 

}
```
So it will be called when available and just skipped otherwise (like on the windows runner)
And then just call strip manually in the github action.

**Comment by AMTitan** [comment]
Ok that should have all the changes, and should work.

**Pull request merged**
